//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqTOSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string cEmployeeCode { get; set; }
        public string vFirstName { get; set; }
        public string vLastName { get; set; }
        public string cCandidateCode { get; set; }
        public string vAddress { get; set; }
        public string cCity { get; set; }
        public string cState { get; set; }
        public string cZip { get; set; }
        public string cCountryCode { get; set; }
        public string cPhone { get; set; }
        public string vQualification { get; set; }
        public Nullable<System.DateTime> dBirthDate { get; set; }
        public string cSex { get; set; }
        public string cCurrentPosition { get; set; }
        public string cDesignation { get; set; }
        public string cEmailId { get; set; }
        public string cDepartmentCode { get; set; }
        public string cRegion { get; set; }
        public byte[] imPhoto { get; set; }
        public Nullable<System.DateTime> dJoiningDate { get; set; }
        public Nullable<System.DateTime> dResignationDate { get; set; }
        public string cSocialSecurityNo { get; set; }
        public string cSupervisorCode { get; set; }
    }
}
